"""create table user_avatars

Revision ID: 670f172b297b
Revises: 69e5754890c6
Create Date: 2025-11-14 19:32:00.626842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '670f172b297b'
down_revision: Union[str, Sequence[str], None] = '69e5754890c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_avatars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('s3_url', sa.String(length=1024), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('size_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_avatars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_avatars_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_avatars_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_avatars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_avatars_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_avatars_id'))

    op.drop_table('user_avatars')
    # ### end Alembic commands ###
