"""create table chats

Revision ID: 69e5754890c6
Revises: e4314fea0cc3
Create Date: 2025-11-14 19:30:18.315769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69e5754890c6'
down_revision: Union[str, Sequence[str], None] = 'e4314fea0cc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user1_id', sa.Integer(), nullable=False),
    sa.Column('user2_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user1_id', 'user2_id', name='unique_chat_users')
    )
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.create_index('idx_user1_user2', ['user1_id', 'user2_id'], unique=False)
        batch_op.create_index('idx_user2_user1', ['user2_id', 'user1_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chats_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chats_id'))
        batch_op.drop_index('idx_user2_user1')
        batch_op.drop_index('idx_user1_user2')

    op.drop_table('chats')
    # ### end Alembic commands ###
